// <auto-generated />
using System;
using BookFlight.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookFlight.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231223171718_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookFlight.Model.BookFlightModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            From = "New York",
                            Time = "12:00 PM",
                            To = "London"
                        },
                        new
                        {
                            Id = 2,
                            From = "Paris",
                            Time = "03:30 PM",
                            To = "Tokyo"
                        },
                        new
                        {
                            Id = 3,
                            From = "New York",
                            Time = "12:17 AM",
                            To = "Houston"
                        },
                        new
                        {
                            Id = 4,
                            From = "Los Angeles",
                            Time = "01:17 AM",
                            To = "Phoenix"
                        },
                        new
                        {
                            Id = 5,
                            From = "Chicago",
                            Time = "02:17 AM",
                            To = "Philadelphia"
                        },
                        new
                        {
                            Id = 6,
                            From = "Houston",
                            Time = "03:17 AM",
                            To = "San Antonio"
                        },
                        new
                        {
                            Id = 7,
                            From = "Phoenix",
                            Time = "04:17 AM",
                            To = "San Diego"
                        },
                        new
                        {
                            Id = 8,
                            From = "Philadelphia",
                            Time = "05:17 AM",
                            To = "Dallas"
                        },
                        new
                        {
                            Id = 9,
                            From = "San Antonio",
                            Time = "06:17 AM",
                            To = "San Jose"
                        },
                        new
                        {
                            Id = 10,
                            From = "San Diego",
                            Time = "07:17 AM",
                            To = "Austin"
                        },
                        new
                        {
                            Id = 11,
                            From = "Dallas",
                            Time = "08:17 AM",
                            To = "Jacksonville"
                        },
                        new
                        {
                            Id = 12,
                            From = "San Jose",
                            Time = "09:17 AM",
                            To = "San Francisco"
                        },
                        new
                        {
                            Id = 13,
                            From = "Austin",
                            Time = "10:17 AM",
                            To = "Indianapolis"
                        },
                        new
                        {
                            Id = 14,
                            From = "Jacksonville",
                            Time = "11:17 AM",
                            To = "Columbus"
                        },
                        new
                        {
                            Id = 15,
                            From = "San Francisco",
                            Time = "12:17 PM",
                            To = "Fort Worth"
                        },
                        new
                        {
                            Id = 16,
                            From = "Indianapolis",
                            Time = "01:17 PM",
                            To = "Charlotte"
                        },
                        new
                        {
                            Id = 17,
                            From = "Columbus",
                            Time = "02:17 PM",
                            To = "Seattle"
                        },
                        new
                        {
                            Id = 18,
                            From = "Fort Worth",
                            Time = "03:17 PM",
                            To = "Denver"
                        },
                        new
                        {
                            Id = 19,
                            From = "Charlotte",
                            Time = "04:17 PM",
                            To = "El Paso"
                        },
                        new
                        {
                            Id = 20,
                            From = "Seattle",
                            Time = "05:17 PM",
                            To = "Detroit"
                        },
                        new
                        {
                            Id = 21,
                            From = "Denver",
                            Time = "06:17 PM",
                            To = "Boston"
                        },
                        new
                        {
                            Id = 22,
                            From = "El Paso",
                            Time = "07:17 PM",
                            To = "Memphis"
                        },
                        new
                        {
                            Id = 23,
                            From = "Detroit",
                            Time = "08:17 PM",
                            To = "Nashville"
                        },
                        new
                        {
                            Id = 24,
                            From = "Boston",
                            Time = "09:17 PM",
                            To = "Dubai"
                        },
                        new
                        {
                            Id = 25,
                            From = "Memphis",
                            Time = "10:17 PM",
                            To = "New York"
                        },
                        new
                        {
                            Id = 26,
                            From = "Nashville",
                            Time = "11:17 PM",
                            To = "Los Angeles"
                        },
                        new
                        {
                            Id = 27,
                            From = "Dubai",
                            Time = "12:17 AM",
                            To = "Chicago"
                        });
                });

            modelBuilder.Entity("BookFlight.Model.Reviews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationInput")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MyReviews")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleInput")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("BookFlight.Model.SearchModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserSearched")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Search");
                });

            modelBuilder.Entity("BookFlight.Model.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
